import { useState, type FormEvent } from "react";
import { Activity, ExternalLink, FileCheck2, Play, Plus, Search, X } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { getGetCheckQueryKey, getListChecksQueryKey, useCreateCheck, useGetCheck, useListChecks, useListServices, useRunCheck } from "@workspace/api-client-react";
import { AppShell, Button, Dialog, EmptyState, ErrorState, FormField, PageHeader, Skeleton, StatusBadge, formatRelative, inputClass } from "@/components/contract-ui";

function CheckDetailDialog({ checkId, onClose }: { checkId: number; onClose: () => void }) {
  const detail = useGetCheck(checkId, { query: { queryKey: getGetCheckQueryKey(checkId) } });
  return <Dialog title={detail.data?.name || "Check details"} detail={detail.data ? `${detail.data.method} ${detail.data.path}` : "Fetching recent run history"} onClose={onClose}>
    {detail.isLoading ? <div className="space-y-3"><Skeleton className="h-20" /><Skeleton className="h-32" /></div> : detail.isError || !detail.data ? <ErrorState retry={() => detail.refetch()} /> : <div><div className="grid grid-cols-3 gap-2"><div className="rounded-md bg-muted p-3"><p className="font-mono text-[9px] text-muted-foreground">SUCCESS</p><p className="mt-1 text-lg font-extrabold">{detail.data.successRate.toFixed(2)}%</p></div><div className="rounded-md bg-muted p-3"><p className="font-mono text-[9px] text-muted-foreground">LATENCY</p><p className="mt-1 text-lg font-extrabold">{detail.data.latency}<span className="text-xs">ms</span></p></div><div className="rounded-md bg-muted p-3"><p className="font-mono text-[9px] text-muted-foreground">URL</p><p className="mt-2 truncate font-mono text-[10px]">{detail.data.url}</p></div></div><h3 className="mb-2 mt-6 text-[12px] font-extrabold">Recent runs</h3><div className="divide-y divide-border rounded-md border border-border">{detail.data.recentRuns?.length ? detail.data.recentRuns.map((run) => <div key={run.id} className="flex items-center gap-3 px-3 py-3" data-testid={`row-check-run-${run.id}`}><StatusBadge status={run.status} kind="run" /><span className="font-mono text-[11px]">{run.statusCode}</span><span className="font-mono text-[11px] text-muted-foreground">{run.latency}ms</span><span className="ml-auto font-mono text-[10px] text-muted-foreground">{formatRelative(run.ranAt)}</span></div>) : <p className="p-4 text-xs text-muted-foreground">No runs have been recorded.</p>}</div></div>}
  </Dialog>;
}

export default function ChecksPage() {
  const queryClient = useQueryClient();
  const checks = useListChecks();
  const services = useListServices();
  const createCheck = useCreateCheck();
  const runCheck = useRunCheck();
  const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [form, setForm] = useState({ serviceId: "", name: "", method: "GET", path: "/", url: "" });
  const data = checks.data || [];
  const filtered = data.filter((check) => `${check.name} ${check.serviceName} ${check.path}`.toLowerCase().includes(search.toLowerCase()));
  const submitCreate = (event: FormEvent) => { event.preventDefault(); createCheck.mutate({ data: { ...form, serviceId: Number(form.serviceId), method: form.method as "GET" | "POST" | "PUT" | "PATCH" | "DELETE" } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListChecksQueryKey() }); setShowCreate(false); setForm({ serviceId: "", name: "", method: "GET", path: "/", url: "" }); } }); };
  if (checks.isLoading) return <AppShell><PageHeader eyebrow="Contract surface" title="API checks" detail="Synthetic checks that keep your contracts honest." /><Skeleton className="h-[340px]" /></AppShell>;
  if (checks.isError) return <AppShell><PageHeader eyebrow="Contract surface" title="API checks" /><ErrorState retry={() => checks.refetch()} /></AppShell>;
  return <AppShell><PageHeader eyebrow="Contract surface / checks" title="API checks" detail="Run a check, inspect its last failures, and spot contract drift before your users do." action={<Button onClick={() => setShowCreate(true)} testId="button-add-check"><Plus size={14} /> Add check</Button>} />
    <div className="mb-5 flex max-w-sm items-center gap-2"><Search size={15} className="text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} className={`${inputClass} py-2`} placeholder="Search checks" data-testid="input-search-checks" /></div>
    {filtered.length ? <div className="overflow-hidden rounded-lg border border-card-border bg-card shadow-xs"><div className="hidden grid-cols-[minmax(220px,1.5fr)_130px_1fr_100px_100px_115px] gap-4 border-b border-border bg-muted/50 px-5 py-3 font-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground md:grid"><span>Check</span><span>Status</span><span>Endpoint</span><span>Latency</span><span>Success</span><span>Last run</span></div><div className="divide-y divide-border">{filtered.map((check) => <div key={check.id} className="grid gap-3 px-5 py-4 md:grid-cols-[minmax(220px,1.5fr)_130px_1fr_100px_100px_115px] md:items-center md:gap-4" data-testid={`row-check-${check.id}`}><button className="flex min-w-0 items-center gap-3 text-left" onClick={() => setSelectedId(check.id)} data-testid={`button-view-check-${check.id}`}><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-accent text-primary"><FileCheck2 size={15} /></div><div className="min-w-0"><p className="truncate text-[12px] font-bold">{check.name}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{check.serviceName}</p></div></button><StatusBadge status={check.status} kind="check" /><div className="flex min-w-0 items-center gap-2 font-mono text-[10px] text-muted-foreground"><span className="rounded bg-muted px-1.5 py-1 text-[9px] font-bold text-foreground">{check.method}</span><span className="truncate">{check.path}</span><a href={check.url} target="_blank" rel="noreferrer" className="shrink-0 text-primary hover:underline" data-testid={`link-check-endpoint-${check.id}`} aria-label="Open endpoint"><ExternalLink size={12} /></a></div><span className="font-mono text-[11px]">{check.latency}ms</span><span className="font-mono text-[11px]">{check.successRate.toFixed(2)}%</span><div className="flex items-center justify-between gap-2"><span className="font-mono text-[10px] text-muted-foreground">{formatRelative(check.lastRunAt)}</span><button onClick={() => runCheck.mutate({ checkId: check.id }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListChecksQueryKey() }); queryClient.invalidateQueries({ queryKey: getGetCheckQueryKey(check.id) }); } })} disabled={runCheck.isPending} className="rounded-md p-1.5 text-primary hover:bg-accent disabled:opacity-50" data-testid={`button-run-check-${check.id}`} aria-label="Run check"><Play size={13} fill="currentColor" /></button></div></div>)}</div></div> : <EmptyState icon={FileCheck2} title={search ? "No matching checks" : "No API checks yet"} detail={search ? "Try a different check name or path." : "Create a check against a production endpoint to start the signal loop."} action={!search && <Button onClick={() => setShowCreate(true)} testId="button-empty-add-check"><Plus size={14} /> Add a check</Button>} />}
    {selectedId !== null && <CheckDetailDialog checkId={selectedId} onClose={() => setSelectedId(null)} />}
    {showCreate && <Dialog title="Add an API check" detail="Checks run against the endpoint you specify." onClose={() => setShowCreate(false)}><form onSubmit={submitCreate} className="space-y-4"><FormField label="Service"><select required value={form.serviceId} onChange={(event) => setForm({ ...form, serviceId: event.target.value })} className={inputClass} data-testid="select-check-service"><option value="">Choose a service</option>{(services.data || []).map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></FormField><FormField label="Check name"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={inputClass} placeholder="e.g. Create session responds" data-testid="input-check-name" /></FormField><div className="grid grid-cols-[100px_1fr] gap-3"><FormField label="Method"><select value={form.method} onChange={(event) => setForm({ ...form, method: event.target.value })} className={inputClass} data-testid="select-check-method"><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></FormField><FormField label="Path"><input required value={form.path} onChange={(event) => setForm({ ...form, path: event.target.value })} className={inputClass} placeholder="/v1/health" data-testid="input-check-path" /></FormField></div><FormField label="Endpoint URL"><input required type="url" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} className={inputClass} placeholder="https://api.example.com/v1/health" data-testid="input-check-url" /></FormField><div className="flex justify-end gap-2 pt-2"><Button variant="secondary" onClick={() => setShowCreate(false)} testId="button-cancel-check">Cancel</Button><Button type="submit" disabled={createCheck.isPending} testId="button-submit-check">{createCheck.isPending ? "Creating…" : "Create check"}</Button></div></form></Dialog>}
  </AppShell>;
}