import { useState, type FormEvent } from "react";
import { Plus, Search, Server } from "lucide-react";
import { getGetServiceQueryKey, getListServicesQueryKey, useCreateService, useGetService, useListServices, useUpdateService } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { AppShell, Button, Dialog, EmptyState, ErrorState, FormField, PageHeader, ServiceMark, Skeleton, StatusBadge, formatRelative, inputClass } from "@/components/contract-ui";

export default function ServicesPage() {
  const queryClient = useQueryClient();
  const services = useListServices();
  const createService = useCreateService();
  const updateService = useUpdateService();
  const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [editing, setEditing] = useState<number | null>(null);
  const [selectedServiceId, setSelectedServiceId] = useState<number | null>(null);
  const selectedService = useGetService(selectedServiceId ?? 0, { query: { enabled: selectedServiceId !== null, queryKey: getGetServiceQueryKey(selectedServiceId ?? 0) } });
  const [form, setForm] = useState({ name: "", owner: "", description: "" });
  const data = services.data || [];
  const filtered = data.filter((service) => `${service.name} ${service.owner} ${service.description || ""}`.toLowerCase().includes(search.toLowerCase()));
  const submitCreate = (event: FormEvent) => { event.preventDefault(); createService.mutate({ data: form }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListServicesQueryKey() }); setShowCreate(false); setForm({ name: "", owner: "", description: "" }); } }); };
  const saveEdit = (event: FormEvent) => { event.preventDefault(); if (editing) updateService.mutate({ serviceId: editing, data: { name: form.name, owner: form.owner, description: form.description } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: getListServicesQueryKey() }); setEditing(null); } }); };
  if (services.isLoading) return <AppShell><PageHeader eyebrow="Catalog" title="Services" detail="The systems your team has decided to watch closely." action={<Button disabled><Plus size={14} /> Add service</Button>} /><div className="rounded-lg border border-card-border bg-card">{[1, 2, 3, 4].map((item) => <div key={item} className="flex gap-4 border-b border-border p-5"><Skeleton className="h-9 w-9" /><div className="flex-1"><Skeleton className="h-4 w-1/3" /><Skeleton className="mt-2 h-3 w-1/2" /></div></div>)}</div></AppShell>;
  if (services.isError) return <AppShell><PageHeader eyebrow="Catalog" title="Services" /><ErrorState retry={() => services.refetch()} /></AppShell>;
  return <AppShell><PageHeader eyebrow="Catalog / monitored surface" title="Services" detail="One place to see ownership, health, and the shape of every API in production." action={<Button onClick={() => { setForm({ name: "", owner: "", description: "" }); setShowCreate(true); }} testId="button-add-service"><Plus size={14} /> Add service</Button>} />
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={search} onChange={(event) => setSearch(event.target.value)} className={`${inputClass} pl-9`} placeholder="Search services or owners" data-testid="input-search-services" /></div></div>
    {filtered.length ? <div className="overflow-hidden rounded-lg border border-card-border bg-card shadow-xs"><div className="hidden grid-cols-[minmax(240px,1.4fr)_1fr_110px_100px_115px_52px] gap-4 border-b border-border bg-muted/50 px-5 py-3 font-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground md:grid"><span>Service</span><span>Owner</span><span>Status</span><span>Uptime</span><span>Updated</span><span /></div><div className="divide-y divide-border">{filtered.map((service) => <div key={service.id} className="grid gap-3 px-5 py-4 transition-colors hover:bg-muted/40 md:grid-cols-[minmax(240px,1.4fr)_1fr_110px_100px_115px_52px] md:items-center md:gap-4" data-testid={`row-service-catalog-${service.id}`}><button onClick={() => setSelectedServiceId(service.id)} className="flex items-center gap-3 text-left" data-testid={`button-view-service-${service.id}`}><ServiceMark name={service.name} /><div><p className="text-[12px] font-bold">{service.name}</p><p className="mt-1 line-clamp-1 text-[10px] text-muted-foreground">{service.description || "No description provided"} · {service.endpointCount} endpoints</p></div></button><span className="text-[11px] text-muted-foreground">{service.owner}</span><StatusBadge status={service.status} /><span className="font-mono text-[11px]">{service.uptime.toFixed(2)}%</span><span className="font-mono text-[10px] text-muted-foreground">{formatRelative(service.updatedAt)}</span><button onClick={() => { setEditing(service.id); setForm({ name: service.name, owner: service.owner, description: service.description || "" }); }} className="justify-self-start rounded-md px-2 py-1 text-[10px] font-bold text-primary hover:bg-accent md:justify-self-end" data-testid={`button-edit-service-${service.id}`}>Edit</button></div>)}</div></div> : <EmptyState icon={Server} title={search ? "No matching services" : "No services in the catalog"} detail={search ? "Try a different name or owner." : "Register the first production API your team wants to keep reliable."} action={!search && <Button onClick={() => setShowCreate(true)} testId="button-empty-add-service"><Plus size={14} /> Add a service</Button>} />}
    {selectedServiceId !== null && <Dialog title={selectedService.data?.name || "Service details"} detail={selectedService.data ? `${selectedService.data.owner} · ${selectedService.data.endpointCount} endpoints` : "Loading service detail"} onClose={() => setSelectedServiceId(null)}>{selectedService.isLoading ? <div className="space-y-3"><Skeleton className="h-16" /><Skeleton className="h-28" /></div> : selectedService.isError || !selectedService.data ? <ErrorState retry={() => selectedService.refetch()} /> : <div className="space-y-4"><div className="flex items-center gap-3"><ServiceMark name={selectedService.data.name} /><div><StatusBadge status={selectedService.data.status} /><p className="mt-2 text-xs text-muted-foreground">{selectedService.data.description || "No description provided."}</p></div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-md bg-muted p-3"><p className="font-mono text-[9px] text-muted-foreground">UPTIME</p><p className="mt-1 text-lg font-extrabold">{selectedService.data.uptime.toFixed(2)}%</p></div><div className="rounded-md bg-muted p-3"><p className="font-mono text-[9px] text-muted-foreground">LATENCY</p><p className="mt-1 text-lg font-extrabold">{selectedService.data.latency}ms</p></div></div></div>}</Dialog>}
    {(showCreate || editing !== null) && <Dialog title={editing !== null ? "Edit service" : "Register a service"} detail="Keep the ownership metadata close to the reliability signal." onClose={() => { setShowCreate(false); setEditing(null); }}><form onSubmit={editing !== null ? saveEdit : submitCreate} className="space-y-4"><FormField label="Service name"><input required minLength={1} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className={inputClass} placeholder="e.g. Identity API" data-testid="input-service-name" /></FormField><FormField label="Owner"><input required minLength={1} value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })} className={inputClass} placeholder="e.g. Platform team" data-testid="input-service-owner" /></FormField><FormField label="Description" hint="A short description helps on-call engineers orient quickly."><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className={`${inputClass} min-h-[82px] resize-y`} placeholder="What does this service do?" data-testid="input-service-description" /></FormField><div className="flex justify-end gap-2 pt-2"><Button variant="secondary" onClick={() => { setShowCreate(false); setEditing(null); }} testId="button-cancel-service">Cancel</Button><Button type="submit" disabled={createService.isPending || updateService.isPending} testId="button-submit-service">{createService.isPending || updateService.isPending ? "Saving…" : editing !== null ? "Save changes" : "Register service"}</Button></div></form></Dialog>}
  </AppShell>;
}